languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Manuel Anrig"
copyright = "© 2025 - Manuel Anrig"

[params]
  dateFormat = "02.01.2006"

  # mainSections = ["section1", "section2"]
  # description = "My awesome website"

[params.author]
   name = "Manuel Anrig"
   image = "img/manuel_sbc_ghibli.png"
   headline = "Tinkering with Tech. Racing on Two Wheels. Living for the Ride"
   bio = """I'm Manuel Anrig, born in '97 and raised on two wheels. 
   From soldering PCBs to shredding trails, my life is a mashup of tech tinkering and bike obsession. 
   After an apprenticeship as an electronics technician and years in PCB design, I swapped the soldering iron 
   for a torque wrench and chased my passion into the bike world. 
   Now, at Specialized, I get to blend both—working on E-Bike System Quality by day and hacking on side projects 
   or racing bikes on the weekend. This site is my corner for blog posts, code experiments, and ride results."""

   links = [
     { email = "mailto:me@manuelanrig.ch" },
     { github = "https://github.com/manupanu" },
     { linkedin = "https://www.linkedin.com/in/manuel-anrig-891853188/" },
     { instagram = "https://www.instagram.com/manuelanrig/" },
   ]
